version: "1"
services:
    - type: web
      name: backend
      runtime: node
      plan: free
      buildCommand: cd frontend && npm install && npm run build
      startCommand: cd backend && npm start
      autoDeploy: true
      envVars:
          - key: NODE_ENV
            value: production
