version: "1"
services:
    - type: web
      name: backend
      runtime: node
      plan: free
      buildCommand: npm install
      startCommand: npm run start
      autoDeploy: true
      envVars:
          - key: NODE_ENV
            value: production

    - type: web
      name: frontend
      runtime: static
      plan: free
      autoDeploy: true
      buildCommand: npm install && npm run build
